#!/usr/bin/env python3
"""Write docs/11-benchmarks.md from the files in results/.

Every number in that document comes from a file this script reads, so the
document cannot say something the measurements did not. Run the measurements
first (see the README in this directory), then:

    python3 report.py
"""

import json
import os
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "docs", "11-benchmarks.md")
BEFORE = "before-3258e8d3"


def load(name, before=False):
    path = os.path.join(HERE, "results", BEFORE if before else "", name)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def n(x):
    return f"{x:,}"


def pct(a, b, digits=1):
    return "–" if not b else f"{100 * a / b:.{digits}f}%"


def usd(x):
    if x >= 1e9:
        return f"${x / 1e9:.2f}B"
    if x >= 1e6:
        return f"${x / 1e6:.1f}M"
    if x >= 1e3:
        return f"${x / 1e3:.0f}K"
    return f"${x:.0f}"


def tally(d):
    return d if isinstance(d, dict) else {}


def main():
    evm, evm0 = load("evm.json"), load("evm.json", True)
    safe, safe0 = load("safe.json"), load("safe.json", True)
    detect, detect0 = load("detect.json"), load("detect.json", True)
    land, land0 = load("landscape.json"), load("landscape.json", True)
    perf = load("perf.json")
    permits = load("permits.json")
    robust = load("robustness.json")
    L = []
    w = L.append

    # ------------------------------------------------------------ totals
    def sum_field(chains, f):
        return sum(c.get(f, 0) for c in chains)

    def merged(chains, f):
        out = {}
        for c in chains:
            for k, v in tally(c.get(f, {})).items():
                out[k] = out.get(k, 0) + v
        return out

    ec, ec0 = evm["chains"], evm0["chains"]
    e_tx = sum_field(ec, "transactions")
    e_proven = sum_field(ec, "payload_proven")
    e_acc, e_acc0 = sum_field(ec, "clearsign_accepted"), sum_field(ec0, "clearsign_accepted")
    e_dig, e_dig_bad = sum_field(ec, "digest_equal"), sum_field(ec, "digest_differs")
    e_special = merged(ec, "chain_specific")
    e_out, e_out0 = merged(ec, "outcome"), merged(ec0, "outcome")
    e_refused0 = merged(ec0, "clearsign_refused")
    e_not_proven = sum_field(ec, "payload_not_proven")

    sc, sc0 = safe["chains"], safe0["chains"]
    s_rec = sum_field(sc, "records")
    s_agree = sum_field(sc, "hash_agree_service")
    s_dis = sum_field(sc, "hash_disagree_service")
    s_alloy = sum_field(sc, "hash_agree_alloy")
    s_conf, s_conf_ok = sum_field(sc, "confirmation_sigs_checked"), sum_field(sc, "confirmation_sigs_recovered_to_owner")
    s_on, s_on_ok = sum_field(sc, "onchain_sigs_checked"), sum_field(sc, "onchain_sigs_recovered_to_owner")
    s_exec = sum_field(sc, "executed")
    s_upgrade = sum_field(sc, "signed_before_upgrade")
    s_auto = sum_field(sc, "auto_domain_agree")
    s_safes = sum(len(c["safes"]) for c in sc)
    s_multisig = sum(len(c["multisig_safes"]) for c in sc)
    s_out, s_out0 = merged(sc, "outcome"), merged(sc0, "outcome")
    s_out_ms = merged(sc, "outcome_multisig_only")
    s_find, s_find0 = merged(sc, "findings"), merged(sc0, "findings")
    s_refused0 = merged(sc0, "parse_refused")
    s_chains_with_records = sum(1 for c in sc if c["records"] > 0)

    land_t = land["total"]
    rep, rep0 = land["replay_outcomes_by_incident"], land0["replay_outcomes_by_incident"]
    rep_total = sum(len(v) for v in rep.values())
    named, named0 = len(rep.get("flagged, mechanism named", [])), len(rep0.get("flagged, mechanism named", []))

    scen = {s["name"]: s for s in perf["scenarios"]}
    thr = perf["corpus_throughput"]

    w("# 11 — Benchmarks: real chains, real attacks, and where a signing reviewer sits")
    w("")
    w("**Generated by `signing-core/bench/report.py` from `signing-core/bench/results/`. Do not edit by hand.**")
    w(f"Data collected 4–5 October 2026; generated {datetime.now(timezone.utc).strftime('%d %B %Y')}.")
    w("")
    w("Four questions, each answered from real data rather than from fixtures chosen to pass:")
    w("")
    w("1. Does the reviewer compute exactly what a signer signs, on every chain it claims?")
    w("2. What does it say about ordinary traffic, and how often does it cry wolf?")
    w("3. Shown the transactions real attacks got people to sign, does it catch them?")
    w("4. Of all the money lost in crypto hacks, how much went through the step it guards?")
    w("")
    w("The method for each is described where its results are, and everything can be rerun:")
    w("see [How to reproduce](#how-to-reproduce). Where the answer is unflattering it is given")
    w("as plainly as where it is not.")
    w("")
    w("## The short version")
    w("")
    w("| | Result |")
    w("|---|---|")
    w(f"| Real transactions, {len(ec)} chains | Committed to exactly the digest the sender signed: **{n(e_dig)} of {n(e_dig + e_dig_bad)}**. "
      f"Accepted {pct(e_acc, e_proven)} of provable transactions (was {pct(e_acc0, e_proven)}) |")
    w(f"| Real Safe transactions, {s_chains_with_records} chains | Hash equal to Safe's service in **{n(s_agree)} of {n(s_agree + s_dis)}**, and to alloy in all. "
      f"**{n(s_conf_ok)} of {n(s_conf)}** owner signatures and **{n(s_on_ok)} of {n(s_on)}** signatures accepted on-chain recover to an owner over the hash it computed |")
    w(f"| Real attacks, replayed | Of {rep_total} signer-deception attacks replayed from the chain, the mechanism was named in **{named}** (was {named0}) |")
    op = land["on_signing_path"]
    w(f"| The hack record, {n(land_t['incidents'])} incidents, {usd(land_t['usd'])} | **{pct(op['incidents'], land_t['incidents'])} of incidents and "
      f"{pct(op['usd'], land_t['usd'])} of value** went through a deceived signer — the only kind of attack a signing reviewer can stop. "
      f"Key theft was {pct(land['by_vector']['KEY_THEFT']['usd'], land_t['usd'])} of value and contract bugs {pct(land['by_vector']['CONTRACT_OR_PROTOCOL_BUG']['usd'], land_t['usd'])} |")
    w(f"| Speed | A Safe review in {scen['safe_bybit']['p50_us']:.0f} µs; {n(round(thr['safe_records'] / thr['safe_seconds']))} real Safe reviews a second on one core |")
    if robust:
        w(f"| Robustness | {robust['fuzz_summary']} Mutation testing: {robust['mutation_summary']} |")
    w("")

    # ------------------------------------------------------------ 1
    w("## 1. Does it compute what the signer actually signs?")
    w("")
    w("A reviewer whose hash is not the hash being signed is worse than none: it gives a")
    w("confident answer about something else. So the first measurement checks the digest")
    w("against the strongest witness available, the signature itself.")
    w("")
    w(f"### Plain transactions: {n(e_tx)} from {len(ec)} chains")
    w("")
    w("Blocks were spread over about two days of each chain's history, ending 2,000 blocks")
    w("behind the head, and every transaction in them was kept up to 1,200 per chain. For")
    w("each one, alloy rebuilt the unsigned payload from the chain's record, and the payload")
    w("was used only if the signature on the chain recovers to the sender over its keccak —")
    w("proof that it is byte for byte what the sender's wallet signed. Then clearsign was")
    w("given those bytes.")
    w("")
    w("| Chain | Transactions | Chain-specific types | Provable | Accepted | Exact digest | Clear | Warning | BLIND | CRITICAL |")
    w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for c in ec:
        o = c["outcome"]
        w(f"| {c['name']} | {n(c['transactions'])} | {n(sum(c['chain_specific'].values()))} | {n(c['payload_proven'])} | "
          f"{n(c['clearsign_accepted'])} | {n(c['digest_equal'])} | {n(o.get('clear', 0))} | {n(o.get('warning', 0))} | "
          f"{n(o.get('blind', 0))} | {n(o.get('critical', 0))} |")
    w(f"| **All** | **{n(e_tx)}** | **{n(sum(e_special.values()))}** | **{n(e_proven)}** | **{n(e_acc)}** | **{n(e_dig)}** | "
      f"**{n(e_out.get('clear', 0))}** | **{n(e_out.get('warning', 0))}** | **{n(e_out.get('blind', 0))}** | **{n(e_out.get('critical', 0))}** |")
    w("")
    refused_desc = ", ".join(f"{k.replace('unsupported transaction type ', 'type ')}: {n(v)}" for k, v in sorted(e_refused0.items()))
    w(f"**Before this round of work, {n(sum(e_refused0.values()))} of these were refused** ({refused_desc}) — EIP-2930, EIP-4844")
    w("and EIP-7702 transactions, which the decoder did not read. They are now decoded, and the")
    w("digest is exact for them too. The 7702 ones matter most: each carries authorizations that")
    w("hand an account to code, and they are now CRITICAL instead of refused.")
    w("")
    w("What could not be tested, and why:")
    w("")
    sp = ", ".join(f"`{k}`: {n(v)}" for k, v in sorted(e_special.items(), key=lambda kv: -kv[1]))
    w(f"- **Chain-specific transaction types ({sp}).** OP Stack deposits (`0x7e`) and Arbitrum's")
    w("  internal transactions (`0x6a`) are made by the system, not signed by anyone. Celo's")
    w("  fee-currency transactions (`0x7b`) and zkSync's EIP-712 transactions (`0x71`) are signed")
    w("  by people, and clearsign cannot read them: a real gap for users of those two chains.")
    w(f"- **{n(e_not_proven)} transactions on Kaia** whose public API presents Kaia's own transaction types as")
    w("  Ethereum legacy ones. Their signed bytes are not Ethereum encodings, so no rebuilt payload")
    w("  recovers to the sender, and they were excluded rather than counted.")
    w("")
    w(f"### Safe transactions: {n(s_rec)} from {s_chains_with_records} chains")
    w("")
    w("Safes were sampled, not chosen: on each chain, every address that emitted Safe's")
    w("`ExecutionSuccess` event in recent blocks was a candidate, and the three busiest plus")
    w("seven at random were taken, with up to 100 of their most recent transactions from Safe's")
    w(f"Transaction Service. That gave {n(s_safes)} Safes, {n(s_multisig)} of them real multisigs with a threshold of")
    w("two or more. Three checks were made on every transaction:")
    w("")
    w("- the hash clearsign computes, against the hash Safe's service published and the hash alloy")
    w("  computes;")
    w("- every owner signature that is an ordinary ECDSA signature, recovered over clearsign's hash;")
    w(f"- for the {n(s_exec)} transactions already executed, the packed signatures the Safe contract itself")
    w("  accepted on-chain, recovered the same way. If clearsign's hash were wrong, they would")
    w("  recover to strangers.")
    w("")
    w("| Chain | Records | Safes | = Safe's service | = alloy | Owner signatures | Signatures accepted on-chain | Clear | Warning | BLIND | CRITICAL |")
    w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for c in sc:
        if c["records"] == 0:
            continue
        o = c["outcome"]
        w(f"| {c['name']} | {n(c['records'])} | {len(c['safes'])} | {n(c['hash_agree_service'])}/{n(c['hash_agree_service'] + c['hash_disagree_service'])} | "
          f"{n(c['hash_agree_alloy'])}/{n(c['hash_agree_alloy'] + c['hash_disagree_alloy'])} | "
          f"{n(c['confirmation_sigs_recovered_to_owner'])}/{n(c['confirmation_sigs_checked'])} | "
          f"{n(c['onchain_sigs_recovered_to_owner'])}/{n(c['onchain_sigs_checked'])} | "
          f"{n(o.get('clear', 0))} | {n(o.get('warning', 0))} | {n(o.get('blind', 0))} | {n(o.get('critical', 0))} |")
    w(f"| **All** | **{n(s_rec)}** | **{n(s_safes)}** | **{n(s_agree)}/{n(s_agree + s_dis)}** | **{n(s_alloy)}/{n(s_rec)}** | "
      f"**{n(s_conf_ok)}/{n(s_conf)}** | **{n(s_on_ok)}/{n(s_on)}** | **{n(s_out.get('clear', 0))}** | **{n(s_out.get('warning', 0))}** | "
      f"**{n(s_out.get('blind', 0))}** | **{n(s_out.get('critical', 0))}** |")
    w("")
    w(f"The previous live comparison covered 238 transactions on Ethereum alone ([09](09-against-real-transactions.md)).")
    w("This one covers every network the application offers except Sepolia, whose log endpoint")
    w("refused the discovery queries, and sixteen more. Two things it found are worth knowing:")
    w("")
    w(f"- **A Safe's domain can change during its life.** One Linea Safe signed its first {s_upgrade} transactions under")
    w("  the v1.1.x domain and every later one under v1.3.0+, because it was upgraded. A tool that")
    w("  takes the version from the Safe's *current* state computes the wrong hash for its history.")
    w("  clearsign settles the domain from the hash the file carries, and got all of them right; the")
    w("  benchmark's own first draft made exactly that mistake, which is how it was found. Each")
    w("  transaction's domain is now settled by the owners' own signatures before anything is compared.")
    s_null = sum(s_refused0.values())
    w(f"- **Safe's service sometimes writes `null` for a zero address.** {n(s_null)} executed Unichain transaction")
    w("  gave `gasToken` and `refundReceiver` as `null`, and the reader refused it. It is now accepted")
    w("  only when the file's own hash proves the zero-address reading, and the review says so.")
    w("")

    # ------------------------------------------------------------ 2
    w("## 2. What it says about ordinary traffic")
    w("")
    w("The same corpora, read for what the reviewer told the person signing.")
    w("")
    w("| | Clear | Warning | BLIND | CRITICAL |")
    w("|---|---:|---:|---:|---:|")
    for label, o in [
        (f"Real transactions ({n(e_acc)} accepted)", e_out),
        (f"Real Safe transactions ({n(s_rec)})", s_out),
        (f"Safe transactions from real multisigs only ({n(sum(s_out_ms.values()))})", s_out_ms),
    ]:
        tot = sum(o.values())
        w(f"| {label} | {pct(o.get('clear', 0), tot)} | {pct(o.get('warning', 0), tot)} | {pct(o.get('blind', 0), tot)} | {pct(o.get('critical', 0), tot)} |")
    w("")
    w("**BLIND is the number to look at.** It is the share of real activity the reviewer cannot")
    w("read: swaps, staking, bridging, account-abstraction bundles and every other function outside")
    w("its verified set. It refuses those rather than guessing, which is the design, but it means")
    w(f"that on {pct(s_out_ms.get('blind', 0), sum(s_out_ms.values()), 0)} of what real multisigs sign, its answer is \"I cannot tell you what this does.\"")
    w("That is the honest size of the gap between this tool and a reviewer that understands DeFi.")
    w("")
    w("**CRITICAL in ordinary traffic is mostly correct.** On Safes it is made of:")
    w("")
    crit_codes = ["UNLIMITED_APPROVAL", "SAFE_DELEGATECALL", "SAFE_OWNER_CHANGE", "APPROVAL_FOR_ALL", "PROXY_UPGRADE",
                  "ROLE_GRANT", "SAFE_THRESHOLD_CHANGE", "SAFE_MODULE_CHANGE", "OWNERSHIP_TRANSFER"]
    w("| Finding | Safe transactions | before this work |")
    w("|---|---:|---:|")
    for c in crit_codes:
        w(f"| `{c}` | {n(s_find.get(c, 0))} | {n(s_find0.get(c, 0))} |")
    w("")
    w("Unlimited approvals, owner changes, upgrades and role grants are exactly what a signer")
    w("should confirm one by one, and they are what the attacks in section 3 used. The exception is")
    w("`SAFE_DELEGATECALL`: most of those are Safe's own helper contracts (SignMessageLib,")
    w("SafeMigration) called the way they are meant to be. Pinning those by address and chain, as")
    w("MultiSend already is, would make that warning more specific; see section 8.")
    w("")
    mal = merged(ec, "findings").get("MALFORMED_ARGUMENTS", 0)
    w(f"**{n(mal)} real transactions called a known function with non-canonical arguments** — almost all a")
    w("`transfer` with extra bytes appended — and were marked CRITICAL. Two applications on Plasma")
    w("and Gnosis account for most; several others carried kilobytes of addresses behind the")
    w("`transfer` selector, the shape of an address-poisoning dispatcher dressed up as a transfer.")
    w("Refusing to call those transfers is the reviewer working as intended.")
    w("")

    # ------------------------------------------------------------ 3
    w("## 3. Real attacks, replayed")
    w("")
    w("The transactions real attacks got people to sign were fetched from the chain and rebuilt")
    w("without trusting any service. A Safe attack was rebuilt from the `execTransaction` calldata")
    w("the chain recorded, decoded by alloy; its nonce and domain, which are not in the calldata,")
    w("were found by search — the right ones reproduce the hash the Safe contract itself emitted —")
    w("and the owners' signatures then had to recover over that hash. A transaction signed by a")
    w("person had to recover to that person. Only then was it shown to the reviewer, once built from")
    w("the code before this work (commit `3258e8d3`) and once from the code after.")
    w("")
    w("| Incident | Chain | Lost | What the victim signed | Before | After |")
    w("|---|---|---:|---|---|---|")
    before = {(o["case"], o["tx"]): o for o in detect0["outcomes"]}
    chain_names = {1: "Ethereum", 56: "BNB Chain", 42161: "Arbitrum", 8453: "Base", 25: "Cronos", 8217: "Kaia", 34443: "Mode"}

    def verdict(o):
        if o["verdict"] == "DO NOT SIGN" and o["specific"]:
            return f"**DO NOT SIGN** — `{o['decisive'][0]}`"
        if o["verdict"] == "DO NOT SIGN":
            return "DO NOT SIGN — BLIND, not decoded"
        if o["verdict"] == "review warnings":
            return f"Warning — `{o['decisive'][0]}`" if o["decisive"] else "Warning"
        if o["verdict"] == "nothing flagged":
            return "Nothing flagged"
        return "Not reviewable"

    seen = set()
    for o in detect["outcomes"]:
        if o["vector"] not in ("SIGNING_DECEPTION_MULTISIG", "SIGNING_DECEPTION_EOA"):
            continue
        b = before.get((o["case"], o["tx"]))
        loss = usd(o["loss_usd"]) if o.get("loss_usd") and o["case"] not in seen else ""
        seen.add(o["case"])
        w(f"| {o['incident']} | {chain_names.get(o['chain_id'], o['chain_id'])} | {loss} | "
          f"{CASE_WHAT.get(o['case'], '')} | {verdict(b) if b else '–'} | {verdict(o)} |")
    w("")
    w(f"**The mechanism was named in {named} of these {rep_total} incidents, up from {named0}.** What changed is")
    w("specificity, not the verdict: before, most of these already ended in DO NOT SIGN, but only")
    w("because the reviewer could not decode them — the same answer it gives to")
    w(f"{pct(s_out_ms.get('blind', 0), sum(s_out_ms.values()), 0)} of ordinary multisig traffic. A warning that fires on most of")
    w("what you sign stops being read. Radiant's signers would have seen \"unknown function\"; they")
    w("now see that they are handing ownership of the protocol to an address they do not control.")
    w("")
    w("The rest, plainly:")
    w("")
    w("- **Nexus Mutual (2020)**: a tampered MetaMask showed the founder one thing and his Ledger signed")
    w("  a plain transfer of 370,000 NXM to the attacker. clearsign shows that transfer and its")
    w("  recipient faithfully — which is the whole defence against a tampered interface — but a token")
    w("  transfer is not itself alarming, so nothing is flagged. Only a person comparing the screen")
    w("  with their intent catches this one.")
    w("- **POAP's founder (2023)**: a bounded `approve` to a drainer gets a WARNING naming the spender,")
    w("  not a refusal: a bounded approval is an ordinary thing to sign.")
    w("- **JayPegs / SushiSwap MISO (2021)**: `createMarket` with the attacker's address injected is")
    w("  outside the verified set, so it is BLIND — refused, but not explained.")
    w("- **KlaySwap (2022)**: Kaia's native transaction format, which clearsign does not read.")
    w("")
    w("**Attacks no reviewer that reads bytes can catch.** In these the transaction said exactly what")
    w("it did, and the victim was wrong about who they were paying:")
    w("")
    w("| Incident | What happened | What clearsign said |")
    w("|---|---|---|")
    for o in detect["outcomes"]:
        if o["vector"] != "DECEIVED_INTENT" or (o["case"], "intent") in seen:
            continue
        seen.add((o["case"], "intent"))
        w(f"| {o['incident']} | {CASE_WHAT.get(o['case'], '')} | {verdict(o)} |")
    w("")
    w("An address-poisoning victim sees the attacker's address in full on clearsign's screen. It")
    w("cannot know that the address is not the one they meant. Defences against this class live")
    w("elsewhere: address books, allowlists, and confirming a recipient over a second channel.")
    w("")
    w("**Not covered at all**, because the victims signed something clearsign does not read: Drift")
    w("(Solana, 2026, about $295M) and SwissBorg (Solana, 2025, $41.5M), both signers deceived into")
    w("approving disguised transactions; DMM Bitcoin (Bitcoin, 2024, $305M); OpenSea's 2022 order")
    w("phishing (`personal_sign`); Monkey Kingdom (Solana).")
    w("")

    # ------------------------------------------------------------ 4
    w("## 4. Where a signing reviewer sits in the hack record")
    w("")
    w(f"DeFiLlama's hack list holds {n(land_t['incidents'])} incidents from 2011 to October 2026, totalling")
    w(f"{usd(land_t['usd'])}. Its labels say what kind of incident each was, not whether a person was")
    w("deceived into signing — \"private key compromised\" covers both a stolen key and a tricked")
    w("signer. So every incident of $1M or more in the ambiguous categories (key compromise, social")
    w("engineering, frontend and infrastructure, access control, governance) was researched one by")
    w(f"one from post-mortems, security firms' write-ups and the chain itself: {n(sum(v['researched'] for v in land['by_vector'].values()))} incidents, of which")
    w(f"{n(sum(1 for x in land['on_signing_path_list'] if x['basis'] == 'researched'))} turned out to have reached the money through a deceived signer. The rest were classified")
    w("by written rules from DeFiLlama's own technique label; the rules are in `bench/landscape.py`")
    w("and the research, with its sources, in `bench/corpus/hacks/`.")
    w("")
    w("| How the attack reached the money | Incidents | Value | Share of value |")
    w("|---|---:|---:|---:|")
    names = {
        "KEY_THEFT": "Key theft — the attacker had the keys and signed for itself",
        "CONTRACT_OR_PROTOCOL_BUG": "Contract or protocol bug — nobody signed anything",
        "SIGNING_DECEPTION_MULTISIG": "**Multisig owners deceived into signing**",
        "SIGNING_DECEPTION_EOA": "**A person deceived into signing**",
        "INSIDER_OR_RUG": "Insider or rug pull",
        "DECEIVED_INTENT": "Deceived about the recipient (address poisoning, impersonation)",
        "GOVERNANCE": "Governance attack",
        "UNKNOWN": "Unknown",
    }
    for k, v in sorted(land["by_vector"].items(), key=lambda kv: -kv[1]["usd"]):
        w(f"| {names.get(k, k)} | {n(v['incidents'])} | {usd(v['usd'])} | {pct(v['usd'], land_t['usd'])} |")
    w("")
    ope = land["on_signing_path_evm"]
    w(f"**A signing reviewer is on the path of {pct(op['incidents'], land_t['incidents'])} of incidents and {pct(op['usd'], land_t['usd'])} of the value lost.**")
    w(f"In formats clearsign reads, {pct(ope['usd'], land_t['usd'])}. That is the ceiling for any tool that works at the moment")
    w("of signing, however good. Another " + pct(land['by_vector']['DECEIVED_INTENT']['usd'], land_t['usd']) + " was lost by people deceived about who they were paying,")
    w("which a reviewer of bytes can show but cannot judge. The rest — most of the money — was taken")
    w("by people who already held the keys, or from contracts nobody had to sign anything to exploit.")
    w("")
    w("The share has not been constant:")
    w("")
    w("| Year | Lost | Through a deceived signer | Key theft | Contract bugs |")
    w("|---|---:|---:|---:|---:|")
    for y, a in land["by_year"].items():
        if int(y) < 2018:
            continue
        tot = a["all"]["usd"]
        w(f"| {y} | {usd(tot)} | {usd(a['on_signing_path']['usd'])} ({pct(a['on_signing_path']['usd'], tot)}) | "
          f"{pct(a['key_theft']['usd'], tot)} | {pct(a['contract_bug']['usd'], tot)} |")
    w("")
    w("Before 2024 almost nothing reached the money this way. In 2025 more than half did — Bybit")
    w("alone — and the industry's own reports agree on the direction: TRM attributes 76% of 2025's")
    w("stolen funds to infrastructure attacks and 12% to code exploits; Chainalysis puts private-key")
    w("compromises at 43.8% of 2024's. Neither separates a stolen key from a deceived signer, which")
    w("is why the incidents were researched here one by one.")
    w("")
    w("**DeFiLlama's list leaves out most retail theft.** Scam Sniffer counts wallet-drainer losses")
    w("of $494M from 332,000 victims in 2024 and $83.85M from 106,106 in 2025. Almost all of that is")
    w("signing deception, and it is the part clearsign can now read: of 2024's large drains, Scam")
    w("Sniffer attributes 56.7% to permit signatures, 31.9% to one DSProxy `setOwner`, and 3.5% to")
    w("`increaseAllowance`; in 2025, Permit and Permit2 were 38% of large drains, with EIP-7702")
    w("batches, `approve`, `transfer` and `setApprovalForAll` behind. Permits, Permit2, `setOwner`,")
    w("`increaseAllowance`, `setApprovalForAll` and 7702 batches are now decoded, and flagged")
    w("CRITICAL by name when they grant unlimited or ownership-level control; a bounded approval")
    w("draws a warning, and a plain `transfer` is shown faithfully but not flagged. Typed data is")
    w("read by the command-line tool, not yet by the window. Sources and dates are in")
    w("`bench/corpus/hacks/loss-landscape-2026-10-05.md`.")
    w("")

    # ------------------------------------------------------------ 5
    w("## 5. Speed and size")
    w("")
    m = perf["machine"]
    w(f"One core of an Apple M5 ({m['logical_cores']} logical cores, {m['os']}/{m['arch']}), release build. Each figure is a")
    w("complete review: parse, decode, judge, hash and render the text a signer reads." +
      (f" Each timing is the median of {['', 'one', 'two', 'three', 'four', 'five'][perf['runs']]} runs."
       if 1 <= perf.get("runs", 0) <= 5 else ""))
    w("")
    w("| Scenario | Input | Median | p99 | Reviews a second | Memory allocated | Peak held |")
    w("|---|---:|---:|---:|---:|---:|---:|")
    for s in perf["scenarios"]:
        w(f"| {s['what']} | {n(s['input_bytes'])} B | {s['p50_us']:.1f} µs | {s['p99_us']:.1f} µs | {n(round(s['reviews_per_second']))} | "
          f"{n(s['bytes_allocated'])} B | {n(s['peak_bytes_held'])} B |")
    w("")
    w(f"Over the real corpora: {n(thr['safe_records'])} Safe transactions in {thr['safe_seconds'] * 1000:.0f} ms "
      f"({n(round(thr['safe_records'] / thr['safe_seconds']))} a second), and {n(thr['evm_transactions'])} plain transactions in "
      f"{thr['evm_seconds'] * 1000:.0f} ms ({n(round(thr['evm_transactions'] / thr['evm_seconds']))} a second).")
    if robust and robust.get("cli"):
        note = robust["cli"].get("note")
        w(f"The command-line tool, started fresh for each review of the Bybit record, takes {robust['cli']['median_ms']:.1f} ms")
        w(f"end to end (median of {n(robust['cli']['runs'])} runs{', ' + note if note else ''}). The binary is {n(robust['cli']['binary_bytes'])} bytes; the WebAssembly reviewer the")
        w(f"window embeds is {n(robust['cli']['wasm_bytes'])} bytes.")
    w("")
    if robust and robust.get("arena"):
        worst = max(robust["arena"], key=lambda a: a["bytes"])
        w("The signer image is held to tighter limits than this table: it takes requests of at most 64 KiB")
        w("and serves each from a 4 MiB arena that never frees, so what counts is everything one review")
        w("allocates, not what it holds at once. Of the largest requests that fit —")
        w(", ".join(a["what"] for a in robust["arena"]) + " —")
        w(f"the most expensive is {worst['what']}, at {n(worst['bytes'])} bytes in total: under the 2 MiB alarm")
        w("`crates/clearsign-ffi/tests/arena_budget.rs` enforces, and inside the arena. (The 1,024-call batch")
        w("above is larger than any request the signer accepts; it is there to time the desktop tools.)")
        w("")

    # ------------------------------------------------------------ 6
    w("## 6. Robustness")
    w("")
    if robust:
        for line in robust.get("lines", []):
            w(line)
        w("")
    w("Differential tests against alloy, an independent and widely used Rust implementation, cover")
    w("everything added in this round: 2,000 random cases each for EIP-2930, EIP-4844 and EIP-7702")
    w("transactions, the administration and permission calls, multicall, and a never-more-permissive")
    w("property on mutated calldata; and 5,000 random EIP-712 documents — nested structs, arrays and")
    w("every atomic type — hashed by both. Two bugs planted in the EIP-712 code (dropping dependent")
    w("types from the type hash; skipping sign extension of negative integers) were each caught at")
    w("once, then removed.")
    w("")
    if permits:
        pv = permits["proven"]
        w(f"Real typed-data signatures: {n(sum(pv.values()))} permits submitted on Ethereum ({', '.join(f'{k}: {n(v)}' for k, v in sorted(pv.items()))})")
        w("were rebuilt from their calldata and hashed by clearsign, and every signature recovered to its")
        w(f"owner{'' if not permits['not_proven'] else ' except ' + ', '.join(f'{n(v)} {k}' for k, v in permits['not_proven'].items())}. Of those, "
          f"{n(permits['unlimited'])} granted an unlimited allowance and would have been CRITICAL; {n(permits['bounded'])} were bounded.")
        w("")

    # ------------------------------------------------------------ 7
    w("## 7. What this does not show")
    w("")
    w("- **It is not an audit.** The code added in this round — the new decoders and the EIP-712")
    w("  reviewer — was written and tested with AI assistance and has not been read by an independent")
    w("  human reviewer. That is still the gate before real funds.")
    w("- **The corpora are samples.** The busiest Safes on a chain are often automation with a")
    w("  threshold of one, which is why multisig-only figures are given separately. Two days of blocks")
    w("  is not a year of them.")
    w(f"- **The attack replay is small.** {rep_total} signer-deception incidents with public, provable")
    w("  transactions. Many attacks never publish theirs, and retail drains are represented by classes")
    w("  of payload rather than by every victim.")
    w("- **The landscape is a classification, with judgement in it.** The research for each incident")
    w("  is published with its sources so the judgements can be checked, and DeFiLlama's own figures")
    w("  are used for amounts even where other sources differ.")
    w("- **Performance is one machine.** Medians are steady from run to run; the p99 column moves with")
    w("  whatever else the machine is doing, and is a ceiling seen once rather than a guarantee.")
    w("- **Typed data is reviewed, not signed,** and only from the command line: the window still reads")
    w("  Safe transactions only, and the signer does not sign typed data.")
    w("")
    w("## 8. What is still open")
    w("")
    w("In rough order of what the measurements say matters:")
    w("")
    w("- **Independent human review** of the code added in this round, and of everything since the")
    w("  September review. Nothing here substitutes for it.")
    w("- **Typed data in the window, and signing bound to that review.** Permit and Permit2 signatures")
    w("  were the largest single class of retail drains in 2024 and 2025, and today only the command")
    w("  line reads them.")
    w("- **Solana and Bitcoin.** Drift (about $295M), SwissBorg ($41.5M) and DMM Bitcoin ($305M) were")
    w("  on the signing path and in formats clearsign does not read.")
    w("- **Safe's own helper contracts** — SignMessageLib, SafeMigration, SafeToL2Migration — pinned by")
    w("  address and chain as MultiSend is, so their DELEGATECALLs are named rather than treated as")
    w("  unknown code.")
    w("- **Celo `0x7b` and zkSync `0x71` transactions**, which people sign and clearsign cannot read.")
    w("- **The BLIND share.** More than half of what real multisigs sign is outside the verified set.")
    w("  Protocol readers (Uniswap, Aave, Lido, bridges) are outside v1's scope; which, if any, belong")
    w("  in it is part of the scope sign-off.")
    w(f"- **Permit severity.** {pct(permits['unlimited'], permits['unlimited'] + permits['bounded'], 0) if permits else 'Most'} of real permits grant an unlimited allowance, so a")
    w("  permit review is CRITICAL most of the time. That follows the rule for approvals, and it may")
    w("  also teach people to click through. The data makes the question concrete; it does not answer it.")
    w("- **Typed-data structures beyond permits**, such as Seaport and UniswapX orders, are shown but BLIND.")
    w("- **Hardware, verified boot and code signing**, unchanged by this work.")
    w("")
    w("## How to reproduce")
    w("")
    w("```sh")
    w("cd signing-core/bench")
    w("python3 collect/safe_corpus.py       # Safe transactions from every chain in collect/chains.py")
    w("python3 collect/evm_corpus.py        # transactions from sampled blocks on the same chains")
    w("python3 collect/attack_corpus.py     # the attack transactions, from the chain")
    w("python3 collect/permit_corpus.py     # permits submitted on Ethereum")
    w("cargo run --release --bin verify-evm")
    w("cargo run --release --bin verify-safe")
    w("cargo run --release --bin detect")
    w("cargo run --release --bin verify-permits")
    w("cargo run --release --bin perf")
    w("python3 landscape.py && python3 report.py")
    w("```")
    w("")
    w("The corpora used for this document are committed under `bench/corpus/`, so everything above")
    w("can be rerun offline; collecting afresh samples newer blocks and will give similar, not")
    w("identical, numbers.")
    with open(OUT, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {os.path.relpath(OUT)}")


CASE_WHAT = {
    "bybit": "Safe `DELEGATECALL` to attacker code, shown as a token transfer",
    "wazirx": "Safe `DELEGATECALL` replacing the implementation, shown as GALA/USDT transfers",
    "radiant-arbitrum": "`transferOwnership` of the protocol's address provider to the attacker",
    "radiant-bsc": "The same ownership transfer on BNB Chain",
    "uniswap-phishing": "`setApprovalForAll` on Uniswap V3 positions to the phisher",
    "badger": "Unlimited `increaseAllowance` to the attacker, from an injected script",
    "nexus-mutual": "A plain transfer of 370,000 NXM to the attacker, behind a tampered MetaMask",
    "poap-rpl": "A bounded `approve` of RPL to a drainer",
    "jaypegs-miso": "MISO `createMarket` with the attacker's address injected",
    "mm-finance": "`approve` to a fake router injected by DNS hijack, then a swap through it",
    "klayswap": "`approve` to a fake factory, from a BGP-hijacked script",
    "eip7702-eth": "The victim's own 7702 account running a batch of approvals",
    "eip7702-base": "The same, on Base",
    "superfortune": "A Safe batch paying a look-alike of the airdrop contract's address",
    "florence": "A Safe USDC transfer to an address-poisoning look-alike",
    "ionic": "An admin Safe listing a counterfeit token as collateral",
    "fake-giwa": "ETH deposited into a fake bridge portal",
    "phantom-galaxies": "A 0.1 ETH \"mint fee\" paid straight to a scammer",
    "eigenlayer": "A Safe batch in which one recipient had been swapped by email",
    "coindash": "ETH sent to the address that replaced the ICO address on a hacked site",
}

if __name__ == "__main__":
    main()
