//! Differential tests against an independent implementation of the same specs.
//!
//! Every UR string in this file was produced by Keystone's reference
//! implementation (`@keystonehq/bc-ur-registry-eth` 0.22.1 with
//! `@ngraveio/bc-ur`), running under Node, and the transaction inside it was
//! produced by Foundry's `cast to-rlp`. Nothing here was generated by this
//! crate. The commands are in `tests/vectors/README.md`.
//!
//! This is the interoperability claim: what MetaMask and Keystone send is what
//! this signer reads, and what this signer sends back is what they accept.

#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::panic
)]

use clearsign_qr::{DataType, Decoder, decode_sign_request, encode_signature};

/// `eth-sign-request` as one QR code.
const SINGLE: &str = "ur:eth-sign-request/osadtpdagdndcawmgtfrkigrpmndutdnbtkgfssbjnaohdjoaoyajnaddrlrfrnysgaelpamztcnpsaelfgmaymwnbroinmeswclluensettntgedmnnpftoenamwmfdlarofyptahnsrkaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeuepmrnwsaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaebsfwfzrtaxaaaaadahtaaddyoeadlecsdwykcsfnykaeykaewkaewkaocycmptfmtiamghwfnetbvwcypmloynwktoimrolfjpkktkzmrhcpiyatisjnihjyhsjnhsjkjewtgucnuy";

/// The same request as an animated sequence of 14 QR codes.
const PARTS: [&str; 14] = [
    "ur:eth-sign-request/1-5/lpadahcsskcywtgucnuyhddeosadtpdagdndcawmgtfrkigrpmndutdnbtkgfssbjnaohdjoaoyajnaddrlrfrnysgaelpamztcnpsaeoedeaemk",
    "ur:eth-sign-request/2-5/lpaoahcsskcywtgucnuyhddelfgmaymwnbroinmeswclluensettntgedmnnpftoenamwmfdlarofyptahnsrkaeaeaeaeaeaeaeaeaehypakpvd",
    "ur:eth-sign-request/3-5/lpaxahcsskcywtgucnuyhddeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeuepmrnwsaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeurgmuohh",
    "ur:eth-sign-request/4-5/lpaaahcsskcywtgucnuyhddeaeaeaeaeaeaeaeaeaeaeaeaebsfwfzrtaxaaaaadahtaaddyoeadlecsdwykcsfnykaeykaewkaewkaorlvaaemd",
    "ur:eth-sign-request/5-5/lpahahcsskcywtgucnuyhddecycmptfmtiamghwfnetbvwcypmloynwktoimrolfjpkktkzmrhcpiyatisjnihjyhsjnhsjkjeaeaeaeoeiniatp",
    "ur:eth-sign-request/6-5/lpamahcsskcywtgucnuyhddelfgmaymwnbroinmeswclluentomuutledpnyqzbynnhsahkscprhtopadtinotfnykaeykaewkaewkaoqdemrktn",
    "ur:eth-sign-request/7-5/lpatahcsskcywtgucnuyhddemkfyoypkjornfsidhkyljtdwiacwdnkbvlwtbngtfpoldaltndndpdrpfpaaswfdmwjnmwjkneaewkaotldityie",
    "ur:eth-sign-request/8-5/lpayahcsskcywtgucnuyhddelfgmaymwnbroinmeswclluentomuutledpnyqzbynnhsahkscprhtopadtinotfnykaeykaewkaewkaolphncwpl",
    "ur:eth-sign-request/9-5/lpasahcsskcywtgucnuyhddemkfyoypkjornfsidhkyljtdwiacwdnkbvlwtbngtfpoldaltndndpdrpfpaaswfdmwjnmwjkneaewkaovljojybe",
    "ur:eth-sign-request/10-5/lpbkahcsskcywtgucnuyhddelfgmaymwnbroinmeswclluensettntgedmnnpftoenamwmfdlarofyptahnsrkaeaeaeaeaeaeaeaeaerhwfynft",
    "ur:eth-sign-request/11-5/lpbdahcsskcywtgucnuyhddefhfekkmycxdacxldbbsfbwiotolayngowyluehhdlycymoylnliaskrljelazctdhyjnbykpiacnhdaonnbkpdty",
    "ur:eth-sign-request/12-5/lpbnahcsskcywtgucnuyhddedagutipawtcnjyknlucyynkiiaayaeoycxvyldtnwfiahlaycxfpotpfaxwemkolfhaejoamaycnhdaoeeheecds",
    "ur:eth-sign-request/13-5/lpbtahcsskcywtgucnuyhdderychjscwlantgacstdwemkgybsgyjectrtbzlymtrlcekkrscfuylyckjtcefgtdhyjnbykpiacnhdaocfmoaepf",
    "ur:eth-sign-request/14-5/lpbaahcsskcywtgucnuyhddelfgmaymwnbroinmeswclluensettntgedmnnpftoenamwmfdlarofyptahnsrkaeaeaeaeaeaeaeaeaediwdeewk",
];

/// The unsigned EIP-1559 transaction inside the request, from `cast to-rlp`.
const UNSIGNED_TX: &str = "0x02f86d012a843b9aca008506fc23ac0082520894a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4880b844a9059cbb00000000000000000000000000000000000000000000000000000000deadbeef00000000000000000000000000000000000000000000000000000000000f4240c0";

/// `eth-signature` CBOR as the reference implementation encodes it.
const SIGNATURE_CBOR: &str = "0xa301d825509b1deb4d3b7d4bad9bdd2b0d7b3dcb6d02584107070707070707070707070707070707070707070707070707070707070707070707070707070707070707070707070707070707070707070707070707070707070369636c6561727369676e";

fn unhex(s: &str) -> Vec<u8> {
    let s = s.strip_prefix("0x").unwrap_or(s);
    (0..s.len() / 2)
        .map(|i| u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap())
        .collect()
}

fn hex(bytes: &[u8]) -> String {
    let mut out = String::from("0x");
    for b in bytes {
        out.push_str(&format!("{b:02x}"));
    }
    out
}

#[test]
fn reads_a_single_part_request_from_the_reference_implementation() {
    let mut decoder = Decoder::new();
    let message = decoder.receive(SINGLE).unwrap().unwrap().to_vec();
    assert_eq!(decoder.ur_type(), Some("eth-sign-request"));

    let request = decode_sign_request(&message).unwrap();
    assert_eq!(request.data_type, DataType::TypedTransaction);
    assert_eq!(hex(&request.sign_data), UNSIGNED_TX);
    assert_eq!(request.chain_id, Some(1));
    assert_eq!(request.path_string(), "m/44'/60'/0'/0/0");
    // The wallet this request was built for: the master fingerprint of the
    // public test phrase, checked independently against BIP-32.
    assert_eq!(request.source_fingerprint, Some(0x16a9_3ed0));
    assert_eq!(
        hex(&request.address.unwrap()),
        "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
    );
    assert_eq!(request.origin.as_deref(), Some("metamask"));
    assert_eq!(
        hex(request.request_id.as_deref().unwrap()),
        "0x9b1deb4d3b7d4bad9bdd2b0d7b3dcb6d"
    );
}

#[test]
fn reads_an_animated_request_one_frame_at_a_time() {
    let mut decoder = Decoder::new();
    let mut message = None;
    for part in PARTS {
        if let Some(m) = decoder.receive(part).unwrap() {
            message = Some(m.to_vec());
            break;
        }
    }
    let request = decode_sign_request(&message.expect("never completed")).unwrap();
    assert_eq!(hex(&request.sign_data), UNSIGNED_TX);
}

#[test]
fn reads_an_animated_request_with_frames_missed_and_out_of_order() {
    // A camera drops frames. The fountain parts must still reconstruct it.
    let mut decoder = Decoder::new();
    let mut message = None;
    let order = [4usize, 0, 13, 2, 9, 12, 6, 11, 10, 8, 7, 5, 3, 1];
    for i in order {
        if i == 1 || i == 3 {
            continue; // two plain fragments never arrive
        }
        if let Some(m) = decoder.receive(PARTS[i]).unwrap() {
            message = Some(m.to_vec());
            break;
        }
    }
    let request = decode_sign_request(&message.expect("never completed")).unwrap();
    assert_eq!(hex(&request.sign_data), UNSIGNED_TX);
}

#[test]
fn the_decoded_transaction_is_the_one_clearsign_reviews() {
    // The whole point of the transport: the bytes that arrive by QR are the
    // bytes that get decoded, displayed and signed.
    let mut decoder = Decoder::new();
    let message = decoder.receive(SINGLE).unwrap().unwrap().to_vec();
    let request = decode_sign_request(&message).unwrap();
    let review = clearsign::review_transaction_bytes(&request.sign_data).unwrap();
    let text = review.render();
    assert!(text.contains("ERC-20 transfer"), "{text}");
    assert!(text.contains("1_000_000"), "{text}");
    assert!(text.contains("0xA0b8 6991"), "{text}");
}

#[test]
fn writes_a_signature_the_reference_implementation_accepts() {
    let signature = [7u8; 65];
    let request_id = unhex("9b1deb4d3b7d4bad9bdd2b0d7b3dcb6d");
    let encoded = encode_signature(Some(&request_id), &signature, Some("clearsign"));
    assert_eq!(hex(&encoded), SIGNATURE_CBOR);
}

#[test]
fn a_request_for_something_other_than_a_transaction_is_named_as_such() {
    // personal_sign and typed data decode, but they are not transactions, and
    // the caller must not treat them as one.
    let mut decoder = Decoder::new();
    let message = decoder.receive(SINGLE).unwrap().unwrap().to_vec();
    let mut mutated = message.clone();
    // The data-type field is a single byte in this encoding: 4 -> 3 (raw bytes).
    let pos = mutated.windows(2).position(|w| w == [0x03, 0x04]).unwrap();
    mutated[pos + 1] = 0x03;
    let request = decode_sign_request(&mutated).unwrap();
    assert_eq!(request.data_type, DataType::RawBytes);
    assert_eq!(request.data_type.label(), "raw message bytes");
}
