#!/usr/bin/env bash
# Generate docs/10-what-is-supported.md from the code.
#
# The deployment table was documented as 1,404 address-chain pairs while the
# code held 2,089. Nobody lied; the table grew and the prose did not. A support
# claim written by hand goes stale the first time somebody edits a list, so this
# reads the numbers out of the source every time — and, where the benchmark has
# been run, the live-chain results out of signing-core/bench/results.
#
# It distinguishes three things a support table usually runs together:
#   listed                the code will act on it
#   tested                a fixture or test exercises it
#   externally checked    compared with an external implementation or record
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
core="$here/.."
repo="$core/.."
out="$repo/docs/10-what-is-supported.md"

tests=$(cd "$core" && cargo test --workspace --release --locked 2>/dev/null | grep -E '^test result' | awk '{s+=$4} END {print s}')

python3 - "$core" "$repo" "$out" "$tests" <<'PY'
import json, os, re, sys
from datetime import datetime, timezone

core, repo, out, tests = sys.argv[1:5]
multisend = open(os.path.join(core, "crates/clearsign/src/multisend.rs"), encoding="utf8").read()
calls = open(os.path.join(core, "crates/clearsign/src/calls.rs"), encoding="utf8").read()
window = open(os.path.join(repo, "app/index.template.html"), encoding="utf8").read()

pairs, chain_ids = 0, set()
for d in re.findall(r"Deployment\s*\{(.*?)\n    \}", multisend, re.S):
    m = re.search(r"chains:\s*&\[(.*?)\]", d, re.S)
    if m:
        ids = re.findall(r"\b\d+\b", m.group(1))
        pairs += len(ids)
        chain_ids.update(ids)
deployments = len(re.findall(r"^    Deployment \{", multisend, re.M))

# Every entry in KNOWN_SIGNATURES, however rustfmt wrapped it. Counting only
# one-line entries once reported 11 when the table held 14.
table = calls[calls.index("pub const KNOWN_SIGNATURES"):]
table = table[: table.index("];")]
selectors = len(re.findall(r"\(\s*(?:crate::multisend::)?SEL_[A-Z0-9_]+\s*,", table))

nets = window[window.index("const NETWORKS = ["):]
nets = nets[: nets.index("\n];")]
network_names = re.findall(r'^\s*\["([^"]+)"', nets, re.M)

# What the benchmark measured on live chains, when its results are present.
results = os.path.join(core, "bench/results")
evm_line = "no live comparison recorded"
safe_line = "**Ethereum mainnet only.** See [09-against-real-transactions.md](09-against-real-transactions.md)"
try:
    evm = json.load(open(os.path.join(results, "evm.json")))
    ch = [c for c in evm["chains"] if c["payload_proven"]]
    evm_line = (f"on {sum(c['payload_proven'] for c in ch):,} real transactions from {len(ch)} chains, "
                f"the digest was exactly what the sender signed in {sum(c['digest_equal'] for c in ch):,} "
                f"([11](11-benchmarks.md))")
except (OSError, KeyError, ValueError):
    pass
try:
    safe = json.load(open(os.path.join(results, "safe.json")))
    ch = [c for c in safe["chains"] if c["records"]]
    safe_line = (f"**{sum(c['hash_agree_service'] for c in ch):,} of {sum(c['records'] for c in ch):,}** real Safe "
                 f"transactions across **{len(ch)} chains** agreed with Safe's service. See [11-benchmarks.md](11-benchmarks.md)")
except (OSError, KeyError, ValueError):
    pass

doc = f"""# 10 — What is supported

**Generated by `signing-core/scripts/support-matrix.sh`. Do not edit by hand.**
Last generated {datetime.now(timezone.utc).strftime("%d %B %Y")}.

Three different things get run together in most support tables, so they are kept
apart here:

| | |
|---|---|
| **Listed** | The code will act on it |
| **Tested** | A fixture or test in this repository exercises it |
| **Externally checked** | Compared with an external implementation or record; not a proof of correctness |

## Chain family

| | |
|---|---|
| Selected EVM formats | Listed, tested, externally checked |
| Bitcoin, Solana, Cosmos, anything non-EVM | **Not supported.** Different transaction models, parsers and signing flows |

## Transaction formats

| Type | | |
|---|---|---|
| Legacy, with and without EIP-155 | Listed, tested, compared with `cast` and `alloy` | |
| `0x01` EIP-2930 | Listed, tested, compared with `alloy` | Access-list transactions |
| `0x02` EIP-1559 | Listed, tested, compared with `cast` and `alloy` | |
| `0x03` EIP-4844 | Listed, tested, compared with `alloy` | Only the blob hashes are signed, and they are shown |
| `0x04` EIP-7702 | Listed, tested, compared with `alloy` | Each authorization is CRITICAL: it hands an account to code |
| Chain-specific types | **Refused** | OP Stack deposits and Arbitrum internal transactions are made by the system; Celo `0x7b` and zkSync `0x71` are signed by people and are not read |

All five Ethereum types, checked live: {evm_line}.

## Calldata

{selectors} selectors are decoded: ERC-20-shaped token calls, token permissions
beyond `approve`, Safe administration, contract administration (ownership,
roles, proxy upgrades and admins), and calls that carry other calls —
MultiSend, `multicall`, timelock `schedule` and `execute`, and smart-account
`execute(bytes32,bytes)`. Every carried call is judged by the same rules.
Anything else is BLIND. The list is `KNOWN_SIGNATURES` in `calls.rs`, and each
entry is checked in tests against both keccak and `cast sig`.

**A decoded selector establishes the shape of a call, not what the code at the
other end does with it.** Nothing in the signed bytes says the address is a
token, and a proxy can point somewhere new between one transaction and the next.
The review says so, as `SELECTOR_IS_NOT_BEHAVIOUR`.

## EIP-712 typed data

Reviewed from the command line (`clearsign typed-data`); not signed, and not yet
read by the window. Hashing is compared with `alloy` on random documents and
with published values. Interpreted: ERC-2612 `Permit`, DAI-style `Permit`,
Permit2 `PermitSingle`, `PermitBatch`, `PermitTransferFrom` and
`PermitBatchTransferFrom`, and Safe's `SafeTx`. Every other structure is shown
field by field and is BLIND.

## Safe

| | |
|---|---|
| Domain versions | v1.1.x, v1.2.0 and v1.3.0+, settled from the hash a record carries. v1.0.0 uses a different struct and is unsupported |
| MultiSend deployments | **{deployments}**, from `safe-global/safe-deployments` |
| Address-chain pairs listed | **{pairs}**, across **{len(chain_ids)}** distinct chain IDs |
| Pairs tested | The ones the batch tests exercise, not all {pairs} |
| Live-record comparisons | {safe_line} |

The allowlist determines where batch decoding is enabled. It does not establish
that every deployment, network or wallet integration has been tested.

## Networks offered in the application

**{len(network_names)}**, chosen explicitly rather than inferred: {", ".join(network_names)}.

Listing a network means the application will fetch and review for it, not that
every pair above has been exercised on it.

## Not supported

Typed-data signing, and typed data in the window. Seaport, UniswapX and other
typed-data structures beyond permits, Permit2 and Safe transactions, which are
shown but BLIND. `personal_sign` messages. Uniswap, bridges and other protocol
decoders. Token names, symbols, decimals and address books. Chain-specific
transaction types. Any network connectivity from the signer.

## Evidence

{tests} tests. See [03-verification-status.md](03-verification-status.md) for
what each one establishes, and what it does not.
"""
open(out, "w").write(doc)
print(f"wrote {out}")
print(f"  deployments={deployments} pairs={pairs} chains={len(chain_ids)} selectors={selectors} "
      f"networks={len(network_names)} tests={tests}")
PY
