#!/usr/bin/env bash
# Generate docs/10-what-is-supported.md from the code.
#
# The deployment table was documented as 1,404 address-chain pairs while the
# code held 2,089. Nobody lied; the table grew and the prose did not. A support
# claim written by hand goes stale the first time somebody edits a list, so this
# reads the numbers out of the source every time.
#
# It distinguishes three things a support table usually runs together:
#   listed    the code will act on it
#   tested    a fixture or test exercises it
#   externally checked    compared with an external implementation or record
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
core="$here/.."
repo="$core/.."
out="$repo/docs/10-what-is-supported.md"

pairs=$(python3 - "$core/crates/clearsign/src/multisend.rs" <<'PY'
import re, sys
s = open(sys.argv[1], encoding='utf8').read()
total = 0
for d in re.findall(r'Deployment\s*\{(.*?)\n    \}', s, re.S):
    m = re.search(r'chains:\s*&\[(.*?)\]', d, re.S)
    if m:
        total += len(re.findall(r'\b\d+\b', m.group(1)))
print(total)
PY
)
chains=$(python3 - "$core/crates/clearsign/src/multisend.rs" <<'PY'
import re, sys
s = open(sys.argv[1], encoding='utf8').read()
seen = set()
for d in re.findall(r'Deployment\s*\{(.*?)\n    \}', s, re.S):
    m = re.search(r'chains:\s*&\[(.*?)\]', d, re.S)
    if m:
        seen.update(re.findall(r'\b\d+\b', m.group(1)))
print(len(seen))
PY
)
# the struct definition is not a deployment
deployments=$(grep -cE '^    Deployment \{' "$core/crates/clearsign/src/multisend.rs")
selectors=$(grep -cE '^\s+\(SEL_[A-Z_]+, "' "$core/crates/clearsign/src/calls.rs" || true)
# the NETWORKS table in the window is the list the application offers
app_networks=$(awk '/^const NETWORKS = \[/{f=1;next} f&&/^\];/{exit} f&&/^  \[/{n++} END{print n+0}' "$repo/app/index.template.html")
network_names=$(awk '/^const NETWORKS = \[/{f=1;next} f&&/^\];/{exit} f&&/^  \["/{match($0,/"[^"]+"/); print substr($0,RSTART+1,RLENGTH-2)}' "$repo/app/index.template.html" | paste -sd, - | sed 's/,/, /g')
tests=$(cd "$core" && cargo test --workspace --release --locked 2>/dev/null | grep -E '^test result' | awk '{s+=$4} END {print s}')

cat > "$out" <<EOF
# 10 — What is supported

**Generated by \`signing-core/scripts/support-matrix.sh\`. Do not edit by hand.**
Last generated $(date -u +"%d %B %Y").

Three different things get run together in most support tables, so they are kept
apart here:

| | |
|---|---|
| **Listed** | The code will act on it |
| **Tested** | A fixture or test in this repository exercises it |
| **Externally checked** | Compared with an external implementation or record; not a proof of correctness |

## Chain family

| | |
|---|---|
| Selected EVM formats | Listed, tested, externally checked |
| Bitcoin, Solana, Cosmos, anything non-EVM | **Not supported.** Different transaction models, parsers and signing flows |

## Transaction formats

| Type | | |
|---|---|---|
| \`0x02\` EIP-1559 | Listed, tested, compared with \`cast\` and \`alloy\` | |
| Legacy | Listed, tested, compared with \`cast\` and \`alloy\` | |
| \`0x01\` EIP-2930 | **Refused** | Access-list transactions |
| \`0x03\` EIP-4844 | **Refused** | Blob transactions |
| \`0x04\` EIP-7702 | **Refused** | Account-delegation authorizations |

A refused type is reported as \`unsupported transaction type 0x0N\` and nothing
is decoded. These are formats within Ethereum, not other chains: "EVM support"
does not mean every Ethereum transaction.

## Calldata

$selectors selectors are decoded. The set is closed for v1; see
[02-v1-scope.md](02-v1-scope.md).

**A decoded selector establishes the shape of a call, not what the code at the
other end does with it.** Nothing in the signed bytes says the address is a
token, and a proxy can point somewhere new between one transaction and the next.
The review says so, as \`SELECTOR_IS_NOT_BEHAVIOUR\`.

## Safe

| | |
|---|---|
| Domain versions | v1.1.x and v1.3.0+. v1.0.0 uses a different struct and is unsupported |
| MultiSend deployments | **$deployments**, from \`safe-global/safe-deployments\` |
| Address-chain pairs listed | **$pairs**, across **$chains** distinct chain IDs |
| Pairs tested | The ones the batch tests exercise, not all $pairs |
| Live-record comparisons | **Ethereum mainnet only.** See [09-against-real-transactions.md](09-against-real-transactions.md) |

The allowlist determines where batch decoding is enabled. It does not establish
that every deployment, network or wallet integration has been tested.

## Networks offered in the application

**$app_networks**, chosen explicitly rather than inferred: $network_names.

Listing a network means
the application will fetch and review for it, not that every pair above has
been exercised on it.

## Not supported

EIP-712 typed data beyond the Safe transaction type. Permit2. Uniswap, bridges
and other protocol decoders. Token names, symbols, decimals and address books.
Any network connectivity from the signer.

## Evidence

$tests tests. See [03-verification-status.md](03-verification-status.md) for
what each one establishes, and what it does not.
EOF
echo "wrote $out"
echo "  deployments=$deployments pairs=$pairs chains=$chains selectors=$selectors networks=$app_networks tests=$tests"
